### PR TITLE
Demography page, Workshop List and guest login changes

### PR DESCRIPTION
**Pull request by argunda1**
This PR contains all changes to
1) Workshop list page - to show today's workshops first and then all other workshops in descending order
2) Fix bugs found on workshop list page:
Date filter is exclusive of both start and end dates - made it inclusive
End date is defaulted to today's date- doesn't work when start date is greater than today's date. Made changes to query by date>=start date when end date is empty.
3) Revoke changes to docker-compose.yml which are not required as per our discussion. 
4) Demography page changes - Label changes to Classroom Observation and Professional Development Certificate Information, remove Gender, Changes to position radio choices - RA after TA and GPTI, and addition of staff, Change of the label Year in Grad School to Year in Grad School/On Campus.
5) Guest login: Add a dummy record with teacher id 0 as attendance record "requires" a teacher id. Frontend and controller changes.

### CODE REVIEW

**Review by trevordimartino — COMMENTED** [review]
Things we talked about today:
* Adding a migration script for the DB changes
* Removing the credits option in attendance list for teachers who are guests
* Make sure that updating an enum column doesn't mess up other records (DB version `mariadb:10`)

**Comment by trevordimartino** [comment]
Things that I can test are:
* logging in as a guest
* logging in as not a guest
* put in a few workshops and see that today's are always on top, regardless of how they're filtered

**Comment by argunda1** [comment]
Addressed the review comments - Added a migration script for DB alterations, removed credits for guests on workshop info page, added changes to read db settings from .env file.

**Review by trevordimartino — APPROVED** [review]
Woot!

**Pull request merged**
